# Config file for automatic testing at travis-ci.com

# safelist
branches:
  only:
  - master
  - dev

matrix:
  include:
    - name: "Python 3.6.5 on macOS (xcode 9.4)"
      os: osx
      osx_image: xcode9.4
      language: shell  # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
#        - pip3 install -U pytest
#        - pip3 install codecov
      install: pip3 install -r requirements.txt
      script: pytest
    - name: "Python 3.7.3 on macOS (xcode 10.2)"
      os: osx
      osx_image: xcode10.2
      language: shell  # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
#        - pip3 install -U pytest
#        - pip3 install codecov
      install: pip3 install -r requirements.txt
      script: pytest
    - name: "Python 3.6 on Linux Xenial"
      os: linux
      language: python
      before_install:
        - python3 --version
        - pip3 install -U pip
      install: pip3 install -r requirements.txt
      script: pytest
    - name: "Python 3.7 on Linux Xenial"
      os: linux
      language: python
      before_install:
        - python3 --version
        - pip3 install -U pip
      install: pip3 install -r requirements.txt
      script: pytest

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
#install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
#script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: robertopreste
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: robertopreste/mtoolnote
    python: 3.6
